import type { AppNotification } from './types'

/** Tuesday 7 October, 09:12. Matches the clock the schedule page starts from. */
export const MOCK_NOW_MS = new Date('2025-10-07T09:12:00').getTime()

export const UNDO_WINDOW_MS = 5000

export const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-02',
    type: 'exception',
    title: 'SLA at risk on M-104 Pump, Site A',
    body: 'Due in 45m. Parts are on site, no one else is assigned.',
    detail:
      'REQ-2047 is due at 09:57 and you are the only tech on it. The pump seal kit is already at Site A, so the job is workable if you start now.',
    requestId: 'REQ-2047',
    machine: 'M-104',
    site: 'A',
    createdAt: '2025-10-07T09:08:00',
    read: false,
    urgent: true,
    sla: true,
    actions: [
      {
        id: 'open',
        label: 'Open job',
        style: 'primary',
        effect: { type: 'toast', message: 'Job details for REQ-2047 are not part of this mock' },
      },
      {
        id: 'help',
        label: 'Ask for help',
        style: 'link',
        effect: { type: 'toast', message: 'Dispatch has been asked to find backup for REQ-2047' },
      },
    ],
  },
  {
    id: 'n-01',
    type: 'assignment',
    title: 'New job assigned: M-211 Compressor, Site B',
    body: 'Will not hold pressure past 6 bar. Window 10:30 to 12:30.',
    detail:
      'Site contact reports the compressor drops out of pressure under load. Seal kit SK-77 is confirmed. This overlaps your 12:00 slot, which dispatch is already moving.',
    requestId: 'REQ-2046',
    machine: 'M-211',
    site: 'B',
    createdAt: '2025-10-07T09:00:00',
    read: false,
    urgent: false,
    replyPrompt: 'Accept or decline M-211, Site B',
    actions: [
      {
        id: 'decline',
        label: 'Decline',
        style: 'ghost',
        effect: { type: 'respond', response: 'declined', tag: 'declined', toast: 'Declined.' },
      },
      {
        id: 'accept',
        label: 'Accept',
        style: 'primary',
        effect: { type: 'respond', response: 'accepted', tag: 'accepted', toast: 'Job accepted' },
      },
    ],
  },
  {
    id: 'n-03',
    type: 'exception',
    title: 'Technician dropped out of REQ-2043',
    body: 'You are the closest available tech to Site C. Dispatch asked if you can take it.',
    detail:
      'The assigned tech was pulled onto an emergency call. The job is a chiller fault at Site C, about 20 minutes from your 08:00 location.',
    requestId: 'REQ-2043',
    machine: 'M-118',
    site: 'C',
    createdAt: '2025-10-07T08:46:00',
    read: false,
    urgent: true,
    replyPrompt: 'Take REQ-2043 at Site C?',
    actions: [
      {
        id: 'take',
        label: 'Take job',
        style: 'primary',
        effect: { type: 'respond', response: 'accepted', tag: 'taken', toast: 'Job taken' },
      },
      {
        id: 'cant',
        label: "Can't",
        style: 'ghost',
        effect: { type: 'respond', response: 'declined', tag: 'declined', toast: 'Declined.' },
      },
    ],
  },
  {
    id: 'n-04',
    type: 'parts',
    title: 'Part unavailable for M-132 Boiler, Site A',
    body: 'Gasket kit GK-220 is backordered. Dispatch is checking Site B stock.',
    detail:
      'Your 15:30 job on M-132 needs GK-220. If Site B has one it can be on your van by lunch, otherwise the job will be pushed to Thursday.',
    requestId: 'REQ-2044',
    machine: 'M-132',
    site: 'A',
    createdAt: '2025-10-07T08:30:00',
    read: false,
    urgent: false,
    actions: [
      {
        id: 'view',
        label: 'View request',
        style: 'link',
        effect: { type: 'toast', message: 'Request details for REQ-2044 are not part of this mock' },
      },
    ],
  },
  {
    id: 'n-05',
    type: 'schedule',
    title: 'Your 12:00 job moved to 12:30',
    body: 'Overlap with M-211 resolved by dispatch.',
    detail: 'REQ-2045 on M-087 now starts at 12:30 and still finishes inside its 16:00 SLA window.',
    requestId: 'REQ-2045',
    machine: 'M-087',
    site: 'C',
    createdAt: '2025-10-07T08:12:00',
    read: false,
    urgent: false,
    actions: [
      {
        id: 'schedule',
        label: 'See schedule',
        style: 'link',
        effect: { type: 'navigate', href: '/technician/schedule' },
      },
    ],
  },
  {
    id: 'n-06',
    type: 'approval',
    title: 'REQ-2048 approved',
    body: 'Parts reserved. You are on the job from 08:00 tomorrow.',
    detail: 'Pump M-056 at Site B. The reserved parts will be in the van locker at the start of your shift.',
    requestId: 'REQ-2048',
    machine: 'M-056',
    site: 'B',
    createdAt: '2025-10-07T07:50:00',
    read: true,
    urgent: false,
    actions: [
      {
        id: 'view',
        label: 'View',
        style: 'link',
        effect: { type: 'toast', message: 'Request details for REQ-2048 are not part of this mock' },
      },
    ],
  },
  {
    id: 'n-07',
    type: 'verification',
    title: 'Completion verified for M-098 Generator, Site B',
    body: 'Task log and 3 photos accepted by ops.',
    detail: 'REQ-2041 closed inside its SLA window. Nothing else needed from you.',
    requestId: 'REQ-2041',
    machine: 'M-098',
    site: 'B',
    createdAt: '2025-10-07T07:20:00',
    read: true,
    urgent: false,
    sla: true,
    actions: [],
  },
  {
    id: 'n-08',
    type: 'system',
    title: 'Shift handover notes added',
    body: 'Read before you start at Site A.',
    detail: 'Night shift left notes on the Site A boiler room: one valve is stiff and the east door sticks.',
    requestId: null,
    machine: null,
    site: 'A',
    createdAt: '2025-10-07T07:00:00',
    read: true,
    urgent: false,
    actions: [],
  },
  {
    id: 'n-09',
    type: 'assignment',
    title: 'New job assigned: M-098 Generator, Site B',
    body: 'Starts 08:00. Fuel line fault reported overnight.',
    detail: 'Fuel line fault reported overnight. Site contact will meet you at the gate.',
    requestId: 'REQ-2041',
    machine: 'M-098',
    site: 'B',
    createdAt: '2025-10-07T06:30:00',
    read: true,
    urgent: false,
    response: 'accepted',
    responseTag: 'accepted',
    actions: [],
  },
  {
    id: 'n-10',
    type: 'assignment',
    title: 'New job assigned: M-142 Compressor, Site C',
    body: 'Intermittent trip on the main breaker. Window 13:00 to 14:30.',
    detail: 'Scheduled for this afternoon at Site C. Breaker panel access needs the site contact on hand.',
    requestId: 'REQ-2040',
    machine: 'M-142',
    site: 'C',
    createdAt: '2025-10-06T16:40:00',
    read: true,
    urgent: false,
    response: 'accepted',
    responseTag: 'accepted',
    actions: [],
  },
  {
    id: 'n-11',
    type: 'schedule',
    title: 'Friday time off confirmed',
    body: 'Dispatch has cleared your calendar. No jobs will be booked.',
    detail: 'Your Friday is blocked as time off. Any jobs that were pencilled in have been moved.',
    requestId: null,
    machine: null,
    site: null,
    createdAt: '2025-10-06T11:15:00',
    read: true,
    urgent: false,
    actions: [
      {
        id: 'schedule',
        label: 'See schedule',
        style: 'link',
        effect: { type: 'navigate', href: '/technician/schedule' },
      },
    ],
  },
  {
    id: 'n-12',
    type: 'parts',
    title: 'Part delivered for M-165 Boiler, Site A',
    body: 'Gasket kit arrived at the depot. Pick it up before Wednesday.',
    detail: 'REQ-2050 starts Wednesday at 08:00. The kit is at the depot front desk, ask for the Site A box.',
    requestId: 'REQ-2050',
    machine: 'M-165',
    site: 'A',
    createdAt: '2025-10-05T15:05:00',
    read: true,
    urgent: false,
    actions: [],
  },
]

export const INCOMING_NOTIFICATION: Omit<AppNotification, 'createdAt'> = {
  id: 'n-13',
  type: 'assignment',
  title: 'Job reassigned to you: M-301 Generator, Site C',
  body: 'Previous tech is out sick. Window 14:30 to 16:00.',
  detail: 'Dispatch moved REQ-2053 onto your afternoon. It fits after M-142 with a 30 minute drive between sites.',
  requestId: 'REQ-2053',
  machine: 'M-301',
  site: 'C',
  read: false,
  urgent: false,
  actions: [
    {
      id: 'view',
      label: 'View request',
      style: 'link',
      effect: { type: 'toast', message: 'Request details for REQ-2053 are not part of this mock' },
    },
  ],
}
